version: '3.8'

services:
  app:
    image: wicklak/docker-mysql-springboot-demo:latest
    container_name: docker-mysql-springboot-demo-app
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/lambda
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: lambda
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: