name: Deploy Spring Boot App With Docker Compose

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: [ubuntu-24.04]
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3

      - name: SetUp Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build Project
        run: mvn clean install -DskipTests

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: docker build -t wicklak/docker-mysql-springboot-demo .

      - name: Push Docker Image
        run: docker push wicklak/docker-mysql-springboot-demo:latest

  deploy:
    needs: build
    runs-on: [ubuntu]
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3

      - name: Install Docker Compose
        run: sudo apt-get update && sudo apt-get install -y docker-compose-plugin

      - name: Pull Docker Image
        run: docker pull wicklak/docker-mysql-springboot-demo:latest

      - name: Stop and Remove Old Containers
        run: docker-compose down || true

      - name: Deploy with Docker Compose
        run: docker-compose up -d
